# 1) build frontend
FROM node:18-alpine AS build
WORKDIR /frontend

COPY frontend/package*.json ./
RUN npm ci

COPY frontend ./
RUN npm run build

# 2) nginx serves dist
FROM nginx:alpine

# replace nginx config
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# copy built frontend
COPY --from=build /frontend/dist /usr/share/nginx/html

EXPOSE 80
